application: head2head-rongdi
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: head2head.app
  
- url: /category.*
  script: category.app
  
- url: /vote.*
  script: vote.app 
  
- url: /item.*
  script: item.app
  
- url: /result.*
  script: result.app  

- url: /export.*
  script: xmlHandler.app 
  
- url: /import.*
  script: xmlHandler.app   

libraries:
- name: webapp2
  version: "2.5.1"